src/meta_memcache/__init__.py, src/meta_memcache/base/connection_pool.py, src/meta_memcache/cache_pools.py, src/meta_memcache/configuration.py, tests/cache_pools_test.py
uhashring's HashRing uses str() on the entities added to the
ring to generate the hashes and the corresponding shardmap.
To mimic bmemcached behavior we need to customize the server
ids we use, so we get exactly the same shard map as before.
In general, controlling the server id can lead to better
management of the pool. If you want, for example, to replace
a server with another, if the server id is kept constant
you avoid any shardmap changes at all.
* Rename IPPort to ServerAddress and also related methods
* Add server_id, so the HashRing behavior can be controlled
easily with the pool configuration
=> Rename IPPort to ServerAddress and add server ids

README.md, src/meta_memcache/base/cache_pool.py, tests/base/cache_pool_test.py
For convenience and simplicity, as most people won't
need advanced routing or unicode keys, the high-level
commands now accept strings as keys.
Internally, it still uses `Key` named tuple.
=> Support strings for keys on high-level commands

README.md, pyproject.toml, src/meta_memcache/__init__.py, src/meta_memcache/base/cache_pool.py, src/meta_memcache/protocol.py, tests/base/cache_pool_test.py
Support the Mode flag on set command to support the
alternative set modes:
Meta flag values:
* E: "add" command. LRU bump and return NS if item exists. Else
add.
* A: "append" command. If item exists, append the new value to its data.
* P: "prepend" command. If item exists, prepend the new value to its data.
* R: "replace" command. Set only if item already exists.
* S: "set" command. The default mode, added for completeness.
This is exposed in the high level API as a `set_mode` argument:
```
def set(
self,
key: Key,
value: Any,  # pyre-ignore[2]
ttl: int,
no_reply: bool = False,
cas_token: Optional[int] = None,
stale_policy: Optional[StalePolicy] = None,
set_mode: SetMode = SetMode.SET,
) -> bool:
```
The `SetMode` enum is:
```
class SetMode(Enum):
SET = b"S"  # Default
ADD = b"E"  # LRU …
```
=> Add set modes (add, replace, append and prepend)

src/meta_memcache/base/cache_pool.py, src/meta_memcache/protocol.py, tests/base/cache_pool_test.py, tests/base/memcache_socket_test.py
Memcache uses `c` to request the cas token, which causes `c<number>`
in the response.
During sets, to properly do a compare-and-swap, `C<number>` has to be
sent.
Before we were using `c` in both cases, which doesn't work.
- Rename `c` in `IntFlags` as `RETURNED_CAS_TOKEN`
- Add `C` `CAS_TOKEN` to `IntFlags` to use it in writes with
compare-and-swap semantics.
=> Fix cas token during set

src/meta_memcache/__init__.py, src/meta_memcache/base/base_cache_pool.py, src/meta_memcache/base/cache_pool.py, src/meta_memcache/base/connection_pool.py, src/meta_memcache/base/memcache_socket.py, src/meta_memcache/configuration.py, src/meta_memcache/protocol.py, tests/base/cache_pool_test.py, tests/base/memcache_socket_test.py
AWS elastic cache only offers ancient version 1.6.6 and breaking
changes were introduced in the meta commands protocol before
declaring it stable.
This implements support for 1.6.6, basically:
- Size in cmd payloads needs to be sent as a flag `cmd S<size>`
instead of the current protocol `cmd <size> <flags>`
- Store success response is `"OK"` instead of `"HD"`.
There are other minor known issues with 1.6.6:
- `Flag.RETURN_CAS_TOKEN` can't be used in meta sets
- CAS token in meta-delete doesn't work
=> Support memcache 1.6.6 meta commands

src/meta_memcache/base/base_cache_pool.py, src/meta_memcache/base/memcache_socket.py, src/meta_memcache/protocol.py, tests/base/cache_pool_test.py, tests/base/memcache_socket_test.py, tests/cache_pools_test.py
See: https://github.com/memcached/memcached/issues/868
TL;DR: Memcache noreply can return error responses on
write commands, defeating the purpose of the noreply
command can causing the response parsing on the socket
to become miss-aligned.
This adds no-op meta command to no-reply write requests.
We can return immediately without waiting
for the response (so there is no roundtrip penalty) and
keep a counter of the pending expected no-op responses.
The next non-noreply command will read and ignore
responses until the no-ops have been read, and proceed
to read the right response to the new command.
- Send no-op after noreply write commands
- Response reads will drop pending responses until the no-op
response when noops are expected in a connection.
=> Handle possible errors during noreply commands

src/meta_memcache/base/memcache_socket.py, tests/base/memcache_socket_test.py
recvmsg_into is one of those low-level that does not
accept named arguments, only positional, and a late
changed to use flag broke large values as result.
- Fix recvmsg_into call, tests
=> recvmsg_into does not accept kwargs

src/meta_memcache/base/base_cache_pool.py
Spaces are not allowed, they will break the protocol
- Check for spaces in keys
=> Check for spaces in keys

pyproject.toml, src/meta_memcache/base/cache_pool.py, src/meta_memcache/base/connection_pool.py, src/meta_memcache/base/memcache_socket.py, tests/cache_pools_test.py
deque seems to work better with gevent, and doesn't
need monkey patching.
- Switch to deque
- Improved errors
=> Switch to deque for ConnectionPool

pyproject.toml, src/meta_memcache/base/base_cache_pool.py, src/meta_memcache/base/memcache_socket.py, src/meta_memcache/protocol.py, tests/base/memcache_socket_test.py
We were resetting the buffer in too many places,
while keeping a memory view with a slice of the
data. This can cause the memory view to end
corrupted, and we change the underlying buffer
contents.
* Only reset buffer before any response processing, so
no more risks of altering the memoryviews created
during response processing.
* Cleanup get_value(), found a more elegant way of
reading the response and avoid using recvmsg_into
that is more complex, harder to mock in tests
and harder to debug.
=> Fix reset buffer issues and cleanup

pyproject.toml, src/meta_memcache/serializer.py, tests/base/cache_pool_test.py
Booleans in python are a subclass of int, so they were
incorrectly serialized.
- Add check for boolean type
=> Fix bool serialization

pyproject.toml, src/meta_memcache/base/connection_pool.py, src/meta_memcache/errors.py
Timeouts on the socket are not correctly wrapped as
MemcacheServerErrors, do they are not handled nicely.
- raise MemcacheServerError wrapping original exception
during the connection context.
=> Wrap timeouts into a MemcacheServerError

.vscode/settings.json, CHANGELOG.md, README.md, pyproject.toml, src/meta_memcache/__init__.py, src/meta_memcache/base/base_cache_pool.py, src/meta_memcache/base/base_write_failure_tracker.py, src/meta_memcache/cache_pools.py, src/meta_memcache/events/__init__.py, src/meta_memcache/events/write_failure_event.py, tests/base/cache_pool_test.py
This PR refactors the write failure tracking to be event-based vs an abstract class based.
After using this feature a bit we noticed some shortcomings with the previous implementation. This change switches to an event based system that allows for as many consumers as need to be notified/take action when a write failure occurs, and reducing some of the complexity of implementing a tracker class.
This does contain a breaking change as it removes the `BaseWriteFailureTracker` class, but the following code can be used to back-port any existing implementations.
```diff
from meta_memcache import BaseWriteFailureTracker, Key
- class CacheFailureTracker(BaseWriteFailureTracker):
+ class CacheFailureTracker(object):
+    def __init__(self, pool: BaseCachePool)-> None:
+        self._pool = pool
+ …
```
=> ♻️ refactor: move from `BaseWriteFailureTracker` to event `OnWriteFailure`

pyproject.toml
This just bumps the version as 0.9.0 was accidentally released when setting up ci/cd
=> 🔖 chore(ver): bump to 0.9.1

CHANGELOG.md, src/meta_memcache/base/base_cache_pool.py
An assumption was made to add `Final` to the `on_write_failure` event in the `BaseCachePool`. This assumption was incorrect and prevents type checks from passing when registering/removing an event handler.
=> ♻️ refactor: remove Final from event so that new handlers can be added or removed

noxfile.py, poetry.lock, pyproject.toml, src/meta_memcache/base/base_cache_pool.py, src/meta_memcache/cache_pools.py, tests/base/cache_pool_test.py
While in some cases we want to capture server errors in application
code (for example to distinguish between actual misses and server
failures), with failure tracker in many cases we want to ignore server errors
and return the appropriate response from the cache pool:
* For failures reading, assume a Miss()
* For writes, assume NotStored().
This simplifies the calling code, that doesn't need to add a try-catch
arround every callsite or write wrappers.
https://revenuecats.atlassian.net/browse/TRIAGE-182
* Add `raise_on_server_error` flag to `BaseCachePool`
* Make base pool ignore `MemcacheServerError` exception when the flag is
set
* Refactor `_exec...()` methods so it is easier to override custom logic
on child classes (for example the gutter routing logic), and thus
avoid repeating the …
=> [TRIAGE-182] Add raise_on_server_error flag to cache pools

src/meta_memcache/base/base_cache_pool.py, src/meta_memcache/base/connection_pool.py, src/meta_memcache/errors.py
We want to handle these errors differently - having a specific subclass will make filtering them cleaner than having to use the error message.
=> Add custom error subclass for when a server is marked down.

pyproject.toml, src/meta_memcache/base/base_cache_pool.py, src/meta_memcache/cache_pools.py
Using typevars allows child classes to work and get
the right type hinting.
Before if you wanted to extend `ShardedCachePool` and use `from_server_addresses`
the type hints on that method will suggest the class is the original class instead of the
new you are just implementing.
=> Use TypeVars for from_server* factory methods

src/meta_memcache/__init__.py, src/meta_memcache/base/cache_pool.py, src/meta_memcache/interfaces/commands.py, src/meta_memcache/interfaces/high_level_commands.py, src/meta_memcache/interfaces/meta_commands.py, src/meta_memcache/protocol.py
Cache pools often need a lot of tweaking and changes. The
application code should only rely on the high-level memcache
protocol, instead of concrete class instances.
This will give us more flexibility to override and implement
different pool behaviors.
- Create interfaces for meta commands, high level commands and
for both.
=> [Refactor] Add Protocol for cache commands

src/meta_memcache/configuration.py, src/meta_memcache/extras/migrating_cache_client.py, tests/migrating_cache_client_test.py
Implements a pool that can switch from one origin pool to a destination
pool smoothly, according to the given configuration.
It has several modes to smooth the transition, being able to warm up
the destination pool before switching reads to it.
=> Add Migrating Cache Pool

README.md, pyproject.toml, src/meta_memcache/__init__.py, src/meta_memcache/commands/high_level_commands.py, src/meta_memcache/interfaces/high_level_commands.py, tests/commands_test.py
Invalidate is an useful high-level method that will return true
if a key is correctly deleted or didn't exist it cache.
- Add invalidate()
=> Add invalidate() high level method

pyproject.toml, src/meta_memcache/__init__.py, src/meta_memcache/connection/memcache_socket.py, tests/memcache_socket_test.py
If the socket is closed unexpectedly we keep trying to read
from socket and keep getting 0 bytes.
- break if we read 0 bytes from socket
=> Fix closed socket detection

pyproject.toml, src/meta_memcache/__init__.py, src/meta_memcache/extras/probabilistic_hot_cache.py, tests/probabilistic_hot_cache_test.py
While rare, a hot entry can get deleted and we need
to clear the hot cache when the origin returns miss
and the revalidation time has elapsed.
=> Clear hot cache on origin miss

pyproject.toml, src/meta_memcache/__init__.py, src/meta_memcache/extras/probabilistic_hot_cache.py, tests/probabilistic_hot_cache_test.py
There was a bug, is_hot was not always properly set for the miss on
multiget
=> Fix cache clear on multi_get misses

pyproject.toml, src/meta_memcache/__init__.py, src/meta_memcache/commands/high_level_commands.py, src/meta_memcache/commands/meta_commands.py, src/meta_memcache/executors/default.py, src/meta_memcache/extras/client_wrapper.py, src/meta_memcache/interfaces/high_level_commands.py, src/meta_memcache/interfaces/meta_commands.py, src/meta_memcache/interfaces/router.py, src/meta_memcache/routers/default.py, src/meta_memcache/routers/ephemeral.py, src/meta_memcache/routers/gutter.py, tests/commands_test.py, tests/probabilistic_hot_cache_test.py
We want to make possible to disable the write failure tracker
for certain commands, so we are exposing the track_write_failures
as a flag in all meta commands.
The rationale for this is that we want the refill write errors
to not cause a write failure and subsequent invalidation.
If a cache is down, reads will cause a miss. This will make
the client read from the backend and attempt to repopulate the
cache. If that write fails, it is fine to ignore it. Recording
it for invalidation might lead to invalidation storms and performance
degradation. Only writes during create, update and delete operations,
when the DB is actually being changed should be tracked as failures.
- Make routers pass the track_write_failure flag to executors
- Make mete commands expose track_write_failure flag
- Make a …
=> Expose track write failures flag in meta-commands

pyproject.toml, src/meta_memcache/__init__.py
When building the package poetry might wrongly
package the wrong way, with src/ prefix if
other files are present in the root folder.
Adding a packages setting on pyproject ensures
poetry won't get confused.
=> Fix poetry build

benchmark.py, src/meta_memcache/connection/providers.py
A NonConsistent hash is more heavy in CPU than a simple crc32 and it can also be less balanced. Since we have plenty of options to manage out pools, we usually grow a pool by migrating into a new one, not expanding a present one, having a simple non-consistent is a good option.
```
INITIAL.multithreaded: Overall: 110779.55 RPS / 9.03 us/req
INITIAL.singlethreaded:Overall: 111545.63 RPS / 8.96 us/req
NON_CONSISTENT_SHARDING.multithreaded:Overall: 124463.31 RPS / 8.03 us/req
NON_CONSISTENT_SHARDING.singlethreaded:Overall: 126979.22 RPS / 7.88 us/req
```
Before:
After:
=> Add NonConsistentHashPoolProvider

src/meta_memcache/commands/high_level_commands.py, src/meta_memcache/connection/memcache_socket.py, src/meta_memcache/protocol.py, tests/probabilistic_hot_cache_test.py
- Copy prebuilt default flags
- Use dataclasses with slots instead of nametuples
Before:
multithreaded: Overall: 124463.31 RPS / 8.03 us/req
singlethreaded: Overall: 126979.22 RPS / 7.88 us/req
After:
multithreaded: Overall: 135509.96 RPS / 7.38 us/req
singlethreaded: Overall: 137630.69 RPS / 7.27 us/req
=> simple optimizations

src/meta_memcache/connection/pool.py, src/meta_memcache/executors/default.py, tests/commands_test.py
Turns out at this micro-optimization level a context manager is quite expensive. It builds an object to encapsulate the context and that adds gc pressure on top of overall slowness. Removing this provides 0.6-0.8us ~10% improvement and softens gc latency spikes in production.
Before:
multithreaded: Overall: 135509.96 RPS / 7.38 us/req
singlethreaded: Overall: 137630.69 RPS / 7.27 us/req
After:
multithreaded: Overall: 151058.43 RPS / 6.62 us/req
singlethreaded: Overall: 151288.67 RPS / 6.61 us/req
Before:
After:
=> Do not use context manager for connection pool borrowing

pyproject.toml, src/meta_memcache/commands/high_level_commands.py, src/meta_memcache/connection/memcache_socket.py, src/meta_memcache/executors/default.py, src/meta_memcache/extras/migrating_cache_client.py, src/meta_memcache/extras/probabilistic_hot_cache.py, src/meta_memcache/protocol.py, tests/commands_test.py, tests/memcache_socket_test.py, tests/migrating_cache_client_test.py, tests/probabilistic_hot_cache_test.py
We spent a lot of time tokenizing and then parsing the response flags.
This does the flag parsing in one single loop, speeding things up.
Also this rewrites response flags not to be Flags/IntFlags as they
can't be used for requests, and having them as part of the Value
dataclass speeds things up as well as simplifies the usage of the
library.
Before:
multithreaded: Overall: 151058.43 RPS / 6.62 us/req
singlethreaded: Overall: 151288.67 RPS / 6.61 us/req
After:
multithreaded: Overall: 193340.40 RPS / 5.17 us/req
singlethreaded: Overall: 193036.56 RPS / 5.18 us/req
Before:
After:
- Avoid header tokenization phase
- Move flags to Success/Value class as attributes
- Move flag parsing to those classes.
=> Refactor response flag parsing

.github/workflows/ci.yml
Github is deprecating NodeJS 16 that is present in some of the
old actions we were using.
Moving to use @main
=> Update actions in CI
